// Mocks generated by Mockito 5.4.6 from annotations
// in leadx_crm/test/data/repositories/customer_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:leadx_crm/data/database/app_database.dart' as _i5;
import 'package:leadx_crm/data/datasources/local/customer_local_data_source.dart'
    as _i3;
import 'package:leadx_crm/data/datasources/local/key_person_local_data_source.dart'
    as _i6;
import 'package:leadx_crm/data/datasources/remote/customer_remote_data_source.dart'
    as _i7;
import 'package:leadx_crm/data/services/sync_service.dart' as _i8;
import 'package:leadx_crm/domain/entities/sync_models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CustomerLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerLocalDataSource extends _i1.Mock
    implements _i3.CustomerLocalDataSource {
  MockCustomerLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.Customer>> watchAllCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCustomers, []),
            returnValue: _i4.Stream<List<_i5.Customer>>.empty(),
          )
          as _i4.Stream<List<_i5.Customer>>);

  @override
  _i4.Stream<List<_i5.Customer>> watchCustomersByRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomersByRm, [rmId]),
            returnValue: _i4.Stream<List<_i5.Customer>>.empty(),
          )
          as _i4.Stream<List<_i5.Customer>>);

  @override
  _i4.Stream<_i5.Customer?> watchCustomerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomerById, [id]),
            returnValue: _i4.Stream<_i5.Customer?>.empty(),
          )
          as _i4.Stream<_i5.Customer?>);

  @override
  _i4.Future<List<_i5.Customer>> getAllCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCustomers, []),
            returnValue: _i4.Future<List<_i5.Customer>>.value(<_i5.Customer>[]),
          )
          as _i4.Future<List<_i5.Customer>>);

  @override
  _i4.Future<_i5.Customer?> getCustomerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerById, [id]),
            returnValue: _i4.Future<_i5.Customer?>.value(),
          )
          as _i4.Future<_i5.Customer?>);

  @override
  _i4.Future<_i5.Customer?> getCustomerByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerByCode, [code]),
            returnValue: _i4.Future<_i5.Customer?>.value(),
          )
          as _i4.Future<_i5.Customer?>);

  @override
  _i4.Future<void> insertCustomer(_i5.CustomersCompanion? customer) =>
      (super.noSuchMethod(
            Invocation.method(#insertCustomer, [customer]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateCustomer(
    String? id,
    _i5.CustomersCompanion? customer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [id, customer]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteCustomer, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> hardDeleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteCustomer, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Customer>> searchCustomers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCustomers, [query]),
            returnValue: _i4.Future<List<_i5.Customer>>.value(<_i5.Customer>[]),
          )
          as _i4.Future<List<_i5.Customer>>);

  @override
  _i4.Future<List<_i5.Customer>> getCustomersByAssignedRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersByAssignedRm, [rmId]),
            returnValue: _i4.Future<List<_i5.Customer>>.value(<_i5.Customer>[]),
          )
          as _i4.Future<List<_i5.Customer>>);

  @override
  _i4.Future<List<_i5.Customer>> getPendingSyncCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCustomers, []),
            returnValue: _i4.Future<List<_i5.Customer>>.value(<_i5.Customer>[]),
          )
          as _i4.Future<List<_i5.Customer>>);

  @override
  _i4.Future<List<_i5.Customer>> getActiveCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCustomers, []),
            returnValue: _i4.Future<List<_i5.Customer>>.value(<_i5.Customer>[]),
          )
          as _i4.Future<List<_i5.Customer>>);

  @override
  _i4.Future<void> markAsSynced(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id, syncedAt]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertCustomers(List<_i5.CustomersCompanion>? customers) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCustomers, [customers]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getPendingSyncCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<DateTime?> getLastSyncTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, []),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);

  @override
  _i4.Future<int> getTotalCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getActiveCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [KeyPersonLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyPersonLocalDataSource extends _i1.Mock
    implements _i6.KeyPersonLocalDataSource {
  MockKeyPersonLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.KeyPerson>> getKeyPersonsByCustomer(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getKeyPersonsByCustomer, [customerId]),
            returnValue: _i4.Future<List<_i5.KeyPerson>>.value(
              <_i5.KeyPerson>[],
            ),
          )
          as _i4.Future<List<_i5.KeyPerson>>);

  @override
  _i4.Stream<List<_i5.KeyPerson>> watchKeyPersonsByCustomer(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchKeyPersonsByCustomer, [customerId]),
            returnValue: _i4.Stream<List<_i5.KeyPerson>>.empty(),
          )
          as _i4.Stream<List<_i5.KeyPerson>>);

  @override
  _i4.Future<List<_i5.KeyPerson>> getKeyPersonsByHvc(String? hvcId) =>
      (super.noSuchMethod(
            Invocation.method(#getKeyPersonsByHvc, [hvcId]),
            returnValue: _i4.Future<List<_i5.KeyPerson>>.value(
              <_i5.KeyPerson>[],
            ),
          )
          as _i4.Future<List<_i5.KeyPerson>>);

  @override
  _i4.Stream<List<_i5.KeyPerson>> watchKeyPersonsByHvc(String? hvcId) =>
      (super.noSuchMethod(
            Invocation.method(#watchKeyPersonsByHvc, [hvcId]),
            returnValue: _i4.Stream<List<_i5.KeyPerson>>.empty(),
          )
          as _i4.Stream<List<_i5.KeyPerson>>);

  @override
  _i4.Future<List<_i5.KeyPerson>> getKeyPersonsByBroker(String? brokerId) =>
      (super.noSuchMethod(
            Invocation.method(#getKeyPersonsByBroker, [brokerId]),
            returnValue: _i4.Future<List<_i5.KeyPerson>>.value(
              <_i5.KeyPerson>[],
            ),
          )
          as _i4.Future<List<_i5.KeyPerson>>);

  @override
  _i4.Future<_i5.KeyPerson?> getKeyPersonById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKeyPersonById, [id]),
            returnValue: _i4.Future<_i5.KeyPerson?>.value(),
          )
          as _i4.Future<_i5.KeyPerson?>);

  @override
  _i4.Future<_i5.KeyPerson?> getPrimaryKeyPerson(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrimaryKeyPerson, [customerId]),
            returnValue: _i4.Future<_i5.KeyPerson?>.value(),
          )
          as _i4.Future<_i5.KeyPerson?>);

  @override
  _i4.Stream<_i5.KeyPerson?> watchPrimaryKeyPerson(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPrimaryKeyPerson, [customerId]),
            returnValue: _i4.Stream<_i5.KeyPerson?>.empty(),
          )
          as _i4.Stream<_i5.KeyPerson?>);

  @override
  _i4.Future<void> insertKeyPerson(_i5.KeyPersonsCompanion? keyPerson) =>
      (super.noSuchMethod(
            Invocation.method(#insertKeyPerson, [keyPerson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateKeyPerson(
    String? id,
    _i5.KeyPersonsCompanion? keyPerson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKeyPerson, [id, keyPerson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteKeyPerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteKeyPerson, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> hardDeleteKeyPerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteKeyPerson, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> clearPrimaryForCustomer(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#clearPrimaryForCustomer, [customerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.KeyPerson>> getPendingSyncKeyPersons() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncKeyPersons, []),
            returnValue: _i4.Future<List<_i5.KeyPerson>>.value(
              <_i5.KeyPerson>[],
            ),
          )
          as _i4.Future<List<_i5.KeyPerson>>);

  @override
  _i4.Future<void> markAsSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertKeyPersons(
    List<_i5.KeyPersonsCompanion>? keyPersons,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertKeyPersons, [keyPersons]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CustomerRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRemoteDataSource extends _i1.Mock
    implements _i7.CustomerRemoteDataSource {
  MockCustomerRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchCustomers({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCustomers, [], {#since: since}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchCustomersByRm(
    String? rmId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCustomersByRm, [rmId], {#since: since}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchCustomerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCustomerById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> createCustomer(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomer, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateCustomer(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [id, data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomer, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> upsertCustomer(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCustomer, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<int> getCustomerCountByRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerCountByRm, [rmId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [KeyPersonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyPersonRemoteDataSource extends _i1.Mock
    implements _i7.KeyPersonRemoteDataSource {
  MockKeyPersonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchKeyPersons({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKeyPersons, [], {#since: since}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchKeyPersonsByCustomer(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKeyPersonsByCustomer, [customerId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchKeyPersonsByHvc(String? hvcId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKeyPersonsByHvc, [hvcId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchKeyPersonsByBroker(
    String? brokerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKeyPersonsByBroker, [brokerId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> createKeyPerson(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createKeyPerson, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateKeyPerson(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKeyPerson, [id, data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteKeyPerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeyPerson, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> upsertKeyPerson(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertKeyPerson, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i8.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.SyncState> get syncStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStateStream),
            returnValue: _i4.Stream<_i2.SyncState>.empty(),
          )
          as _i4.Stream<_i2.SyncState>);

  @override
  _i2.SyncState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _i9.dummyValue<_i2.SyncState>(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i2.SyncState);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.SyncResult> processQueue() =>
      (super.noSuchMethod(
            Invocation.method(#processQueue, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(this, Invocation.method(#processQueue, [])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> triggerSync() =>
      (super.noSuchMethod(
            Invocation.method(#triggerSync, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(this, Invocation.method(#triggerSync, [])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  void startBackgroundSync({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(#startBackgroundSync, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );

  @override
  void stopBackgroundSync() => super.noSuchMethod(
    Invocation.method(#stopBackgroundSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<int> queueOperation({
    required _i2.SyncEntityType? entityType,
    required String? entityId,
    required _i2.SyncOperation? operation,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueOperation, [], {
              #entityType: entityType,
              #entityId: entityId,
              #operation: operation,
              #payload: payload,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<int> watchPendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchPendingCount, []),
            returnValue: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);

  @override
  _i4.Future<int> getPendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
