// Mocks generated by Mockito 5.4.6 from annotations
// in leadx_crm/test/data/repositories/pipeline_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:leadx_crm/data/database/app_database.dart' as _i5;
import 'package:leadx_crm/data/datasources/local/master_data_local_data_source.dart'
    as _i6;
import 'package:leadx_crm/data/datasources/local/pipeline_local_data_source.dart'
    as _i3;
import 'package:leadx_crm/data/datasources/remote/pipeline_remote_data_source.dart'
    as _i8;
import 'package:leadx_crm/data/dtos/master_data_dtos.dart' as _i7;
import 'package:leadx_crm/data/services/sync_service.dart' as _i9;
import 'package:leadx_crm/domain/entities/sync_models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PipelineLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPipelineLocalDataSource extends _i1.Mock
    implements _i3.PipelineLocalDataSource {
  MockPipelineLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.Pipeline>> watchAllPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPipelines, []),
            returnValue: _i4.Stream<List<_i5.Pipeline>>.empty(),
          )
          as _i4.Stream<List<_i5.Pipeline>>);

  @override
  _i4.Stream<List<_i5.Pipeline>> watchCustomerPipelines(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomerPipelines, [customerId]),
            returnValue: _i4.Stream<List<_i5.Pipeline>>.empty(),
          )
          as _i4.Stream<List<_i5.Pipeline>>);

  @override
  _i4.Stream<List<_i5.Pipeline>> watchPipelinesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPipelinesByStage, [stageId]),
            returnValue: _i4.Stream<List<_i5.Pipeline>>.empty(),
          )
          as _i4.Stream<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.Pipeline>> getAllPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPipelines, []),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<_i5.Pipeline?> getPipelineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineById, [id]),
            returnValue: _i4.Future<_i5.Pipeline?>.value(),
          )
          as _i4.Future<_i5.Pipeline?>);

  @override
  _i4.Future<_i5.Pipeline?> getPipelineByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineByCode, [code]),
            returnValue: _i4.Future<_i5.Pipeline?>.value(),
          )
          as _i4.Future<_i5.Pipeline?>);

  @override
  _i4.Future<List<_i5.Pipeline>> getCustomerPipelines(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPipelines, [customerId]),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<void> insertPipeline(_i5.PipelinesCompanion? pipeline) =>
      (super.noSuchMethod(
            Invocation.method(#insertPipeline, [pipeline]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePipeline(
    String? id,
    _i5.PipelinesCompanion? pipeline,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePipeline, [id, pipeline]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDeletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeletePipeline, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> hardDeletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeletePipeline, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Pipeline>> searchPipelines(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPipelines, [query]),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.Pipeline>> getPipelinesByAssignedRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelinesByAssignedRm, [rmId]),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.Pipeline>> getPipelinesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelinesByStage, [stageId]),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.Pipeline>> getBrokerPipelines(String? brokerId) =>
      (super.noSuchMethod(
            Invocation.method(#getBrokerPipelines, [brokerId]),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.Pipeline>> getPendingSyncPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncPipelines, []),
            returnValue: _i4.Future<List<_i5.Pipeline>>.value(<_i5.Pipeline>[]),
          )
          as _i4.Future<List<_i5.Pipeline>>);

  @override
  _i4.Future<List<_i5.PipelineStage>> getPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStages, []),
            returnValue: _i4.Future<List<_i5.PipelineStage>>.value(
              <_i5.PipelineStage>[],
            ),
          )
          as _i4.Future<List<_i5.PipelineStage>>);

  @override
  _i4.Future<List<_i5.PipelineStatuse>> getPipelineStatuses({
    String? stageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStatuses, [], {#stageId: stageId}),
            returnValue: _i4.Future<List<_i5.PipelineStatuse>>.value(
              <_i5.PipelineStatuse>[],
            ),
          )
          as _i4.Future<List<_i5.PipelineStatuse>>);

  @override
  _i4.Future<_i5.PipelineStage?> getStageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStageById, [id]),
            returnValue: _i4.Future<_i5.PipelineStage?>.value(),
          )
          as _i4.Future<_i5.PipelineStage?>);

  @override
  _i4.Future<_i5.PipelineStatuse?> getDefaultStatus(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultStatus, [stageId]),
            returnValue: _i4.Future<_i5.PipelineStatuse?>.value(),
          )
          as _i4.Future<_i5.PipelineStatuse?>);

  @override
  _i4.Future<void> markAsSynced(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id, syncedAt]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertPipelines(List<_i5.PipelinesCompanion>? pipelines) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPipelines, [pipelines]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getPendingSyncCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<DateTime?> getLastSyncTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, []),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);

  @override
  _i4.Future<int> getTotalCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getCountByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getCountByStage, [stageId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getCustomerPipelineCount(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPipelineCount, [customerId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [MasterDataLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterDataLocalDataSource extends _i1.Mock
    implements _i6.MasterDataLocalDataSource {
  MockMasterDataLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.ProvinceDto>> getProvinces() =>
      (super.noSuchMethod(
            Invocation.method(#getProvinces, []),
            returnValue: _i4.Future<List<_i7.ProvinceDto>>.value(
              <_i7.ProvinceDto>[],
            ),
          )
          as _i4.Future<List<_i7.ProvinceDto>>);

  @override
  _i4.Stream<List<_i7.ProvinceDto>> watchProvinces() =>
      (super.noSuchMethod(
            Invocation.method(#watchProvinces, []),
            returnValue: _i4.Stream<List<_i7.ProvinceDto>>.empty(),
          )
          as _i4.Stream<List<_i7.ProvinceDto>>);

  @override
  _i4.Future<List<_i7.CityDto>> getCitiesByProvince(String? provinceId) =>
      (super.noSuchMethod(
            Invocation.method(#getCitiesByProvince, [provinceId]),
            returnValue: _i4.Future<List<_i7.CityDto>>.value(<_i7.CityDto>[]),
          )
          as _i4.Future<List<_i7.CityDto>>);

  @override
  _i4.Stream<List<_i7.CityDto>> watchCitiesByProvince(String? provinceId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCitiesByProvince, [provinceId]),
            returnValue: _i4.Stream<List<_i7.CityDto>>.empty(),
          )
          as _i4.Stream<List<_i7.CityDto>>);

  @override
  _i4.Future<List<_i7.CompanyTypeDto>> getCompanyTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyTypes, []),
            returnValue: _i4.Future<List<_i7.CompanyTypeDto>>.value(
              <_i7.CompanyTypeDto>[],
            ),
          )
          as _i4.Future<List<_i7.CompanyTypeDto>>);

  @override
  _i4.Stream<List<_i7.CompanyTypeDto>> watchCompanyTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchCompanyTypes, []),
            returnValue: _i4.Stream<List<_i7.CompanyTypeDto>>.empty(),
          )
          as _i4.Stream<List<_i7.CompanyTypeDto>>);

  @override
  _i4.Future<List<_i7.OwnershipTypeDto>> getOwnershipTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getOwnershipTypes, []),
            returnValue: _i4.Future<List<_i7.OwnershipTypeDto>>.value(
              <_i7.OwnershipTypeDto>[],
            ),
          )
          as _i4.Future<List<_i7.OwnershipTypeDto>>);

  @override
  _i4.Stream<List<_i7.OwnershipTypeDto>> watchOwnershipTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchOwnershipTypes, []),
            returnValue: _i4.Stream<List<_i7.OwnershipTypeDto>>.empty(),
          )
          as _i4.Stream<List<_i7.OwnershipTypeDto>>);

  @override
  _i4.Future<List<_i7.IndustryDto>> getIndustries() =>
      (super.noSuchMethod(
            Invocation.method(#getIndustries, []),
            returnValue: _i4.Future<List<_i7.IndustryDto>>.value(
              <_i7.IndustryDto>[],
            ),
          )
          as _i4.Future<List<_i7.IndustryDto>>);

  @override
  _i4.Stream<List<_i7.IndustryDto>> watchIndustries() =>
      (super.noSuchMethod(
            Invocation.method(#watchIndustries, []),
            returnValue: _i4.Stream<List<_i7.IndustryDto>>.empty(),
          )
          as _i4.Stream<List<_i7.IndustryDto>>);

  @override
  _i4.Future<List<_i7.CobDto>> getCobs() =>
      (super.noSuchMethod(
            Invocation.method(#getCobs, []),
            returnValue: _i4.Future<List<_i7.CobDto>>.value(<_i7.CobDto>[]),
          )
          as _i4.Future<List<_i7.CobDto>>);

  @override
  _i4.Stream<List<_i7.CobDto>> watchCobs() =>
      (super.noSuchMethod(
            Invocation.method(#watchCobs, []),
            returnValue: _i4.Stream<List<_i7.CobDto>>.empty(),
          )
          as _i4.Stream<List<_i7.CobDto>>);

  @override
  _i4.Future<List<_i7.LobDto>> getLobsByCob(String? cobId) =>
      (super.noSuchMethod(
            Invocation.method(#getLobsByCob, [cobId]),
            returnValue: _i4.Future<List<_i7.LobDto>>.value(<_i7.LobDto>[]),
          )
          as _i4.Future<List<_i7.LobDto>>);

  @override
  _i4.Stream<List<_i7.LobDto>> watchLobsByCob(String? cobId) =>
      (super.noSuchMethod(
            Invocation.method(#watchLobsByCob, [cobId]),
            returnValue: _i4.Stream<List<_i7.LobDto>>.empty(),
          )
          as _i4.Stream<List<_i7.LobDto>>);

  @override
  _i4.Future<List<_i7.LobDto>> getAllLobs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLobs, []),
            returnValue: _i4.Future<List<_i7.LobDto>>.value(<_i7.LobDto>[]),
          )
          as _i4.Future<List<_i7.LobDto>>);

  @override
  _i4.Future<List<_i7.PipelineStageDto>> getPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStages, []),
            returnValue: _i4.Future<List<_i7.PipelineStageDto>>.value(
              <_i7.PipelineStageDto>[],
            ),
          )
          as _i4.Future<List<_i7.PipelineStageDto>>);

  @override
  _i4.Stream<List<_i7.PipelineStageDto>> watchPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#watchPipelineStages, []),
            returnValue: _i4.Stream<List<_i7.PipelineStageDto>>.empty(),
          )
          as _i4.Stream<List<_i7.PipelineStageDto>>);

  @override
  _i4.Future<List<_i7.PipelineStatusDto>> getStatusesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getStatusesByStage, [stageId]),
            returnValue: _i4.Future<List<_i7.PipelineStatusDto>>.value(
              <_i7.PipelineStatusDto>[],
            ),
          )
          as _i4.Future<List<_i7.PipelineStatusDto>>);

  @override
  _i4.Future<List<_i7.ActivityTypeDto>> getActivityTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getActivityTypes, []),
            returnValue: _i4.Future<List<_i7.ActivityTypeDto>>.value(
              <_i7.ActivityTypeDto>[],
            ),
          )
          as _i4.Future<List<_i7.ActivityTypeDto>>);

  @override
  _i4.Stream<List<_i7.ActivityTypeDto>> watchActivityTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchActivityTypes, []),
            returnValue: _i4.Stream<List<_i7.ActivityTypeDto>>.empty(),
          )
          as _i4.Stream<List<_i7.ActivityTypeDto>>);

  @override
  _i4.Future<List<_i7.LeadSourceDto>> getLeadSources() =>
      (super.noSuchMethod(
            Invocation.method(#getLeadSources, []),
            returnValue: _i4.Future<List<_i7.LeadSourceDto>>.value(
              <_i7.LeadSourceDto>[],
            ),
          )
          as _i4.Future<List<_i7.LeadSourceDto>>);

  @override
  _i4.Stream<List<_i7.LeadSourceDto>> watchLeadSources() =>
      (super.noSuchMethod(
            Invocation.method(#watchLeadSources, []),
            returnValue: _i4.Stream<List<_i7.LeadSourceDto>>.empty(),
          )
          as _i4.Stream<List<_i7.LeadSourceDto>>);

  @override
  _i4.Future<List<_i7.DeclineReasonDto>> getDeclineReasons() =>
      (super.noSuchMethod(
            Invocation.method(#getDeclineReasons, []),
            returnValue: _i4.Future<List<_i7.DeclineReasonDto>>.value(
              <_i7.DeclineReasonDto>[],
            ),
          )
          as _i4.Future<List<_i7.DeclineReasonDto>>);

  @override
  _i4.Future<List<_i7.HvcTypeDto>> getHvcTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getHvcTypes, []),
            returnValue: _i4.Future<List<_i7.HvcTypeDto>>.value(
              <_i7.HvcTypeDto>[],
            ),
          )
          as _i4.Future<List<_i7.HvcTypeDto>>);

  @override
  _i4.Stream<List<_i7.HvcTypeDto>> watchHvcTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchHvcTypes, []),
            returnValue: _i4.Stream<List<_i7.HvcTypeDto>>.empty(),
          )
          as _i4.Stream<List<_i7.HvcTypeDto>>);

  @override
  _i4.Future<List<_i5.Broker>> getBrokers() =>
      (super.noSuchMethod(
            Invocation.method(#getBrokers, []),
            returnValue: _i4.Future<List<_i5.Broker>>.value(<_i5.Broker>[]),
          )
          as _i4.Future<List<_i5.Broker>>);

  @override
  _i4.Stream<List<_i5.Broker>> watchBrokers() =>
      (super.noSuchMethod(
            Invocation.method(#watchBrokers, []),
            returnValue: _i4.Stream<List<_i5.Broker>>.empty(),
          )
          as _i4.Stream<List<_i5.Broker>>);

  @override
  _i4.Future<void> upsertProvinces(List<_i5.ProvincesCompanion>? provinces) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProvinces, [provinces]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertCities(List<_i5.CitiesCompanion>? cities) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCities, [cities]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertCompanyTypes(List<_i5.CompanyTypesCompanion>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCompanyTypes, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertOwnershipTypes(
    List<_i5.OwnershipTypesCompanion>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertOwnershipTypes, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertIndustries(List<_i5.IndustriesCompanion>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertIndustries, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i7.RegionalOfficeDto>> watchRegionalOffices() =>
      (super.noSuchMethod(
            Invocation.method(#watchRegionalOffices, []),
            returnValue: _i4.Stream<List<_i7.RegionalOfficeDto>>.empty(),
          )
          as _i4.Stream<List<_i7.RegionalOfficeDto>>);

  @override
  _i4.Stream<List<_i7.BranchDto>> watchBranches() =>
      (super.noSuchMethod(
            Invocation.method(#watchBranches, []),
            returnValue: _i4.Stream<List<_i7.BranchDto>>.empty(),
          )
          as _i4.Stream<List<_i7.BranchDto>>);
}

/// A class which mocks [PipelineRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPipelineRemoteDataSource extends _i1.Mock
    implements _i8.PipelineRemoteDataSource {
  MockPipelineRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPipelines({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelines, [], {#since: since}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPipelinesByCustomer(
    String? customerId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchPipelinesByCustomer,
              [customerId],
              {#since: since},
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPipelinesByRm(
    String? rmId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelinesByRm, [rmId], {#since: since}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchPipelineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelineById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> createPipeline(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createPipeline, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updatePipeline(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePipeline, [id, data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePipeline, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> upsertPipeline(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPipeline, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<int> getPipelineCountByCustomer(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineCountByCustomer, [customerId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getPipelineCountByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineCountByStage, [stageId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i9.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.SyncState> get syncStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStateStream),
            returnValue: _i4.Stream<_i2.SyncState>.empty(),
          )
          as _i4.Stream<_i2.SyncState>);

  @override
  _i2.SyncState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _i10.dummyValue<_i2.SyncState>(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i2.SyncState);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.SyncResult> processQueue() =>
      (super.noSuchMethod(
            Invocation.method(#processQueue, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(this, Invocation.method(#processQueue, [])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> triggerSync() =>
      (super.noSuchMethod(
            Invocation.method(#triggerSync, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(this, Invocation.method(#triggerSync, [])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  void startBackgroundSync({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(#startBackgroundSync, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );

  @override
  void stopBackgroundSync() => super.noSuchMethod(
    Invocation.method(#stopBackgroundSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<int> queueOperation({
    required _i2.SyncEntityType? entityType,
    required String? entityId,
    required _i2.SyncOperation? operation,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueOperation, [], {
              #entityType: entityType,
              #entityId: entityId,
              #operation: operation,
              #payload: payload,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<int> watchPendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchPendingCount, []),
            returnValue: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);

  @override
  _i4.Future<int> getPendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
