// Mocks generated by Mockito 5.4.6 from annotations
// in leadx_crm/test/integration/pipeline_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:leadx_crm/data/database/app_database.dart' as _i3;
import 'package:leadx_crm/data/datasources/local/customer_local_data_source.dart'
    as _i10;
import 'package:leadx_crm/data/datasources/local/master_data_local_data_source.dart'
    as _i8;
import 'package:leadx_crm/data/datasources/local/pipeline_local_data_source.dart'
    as _i7;
import 'package:leadx_crm/data/datasources/remote/pipeline_remote_data_source.dart'
    as _i11;
import 'package:leadx_crm/data/dtos/master_data_dtos.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:supabase_flutter/supabase_flutter.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RegionalOfficesTable_1 extends _i1.SmartFake
    implements _i3.$RegionalOfficesTable {
  _Fake$RegionalOfficesTable_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BranchesTable_2 extends _i1.SmartFake
    implements _i3.$BranchesTable {
  _Fake$BranchesTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_3 extends _i1.SmartFake implements _i3.$UsersTable {
  _Fake$UsersTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserHierarchyTable_4 extends _i1.SmartFake
    implements _i3.$UserHierarchyTable {
  _Fake$UserHierarchyTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProvincesTable_5 extends _i1.SmartFake
    implements _i3.$ProvincesTable {
  _Fake$ProvincesTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CitiesTable_6 extends _i1.SmartFake implements _i3.$CitiesTable {
  _Fake$CitiesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CompanyTypesTable_7 extends _i1.SmartFake
    implements _i3.$CompanyTypesTable {
  _Fake$CompanyTypesTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OwnershipTypesTable_8 extends _i1.SmartFake
    implements _i3.$OwnershipTypesTable {
  _Fake$OwnershipTypesTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$IndustriesTable_9 extends _i1.SmartFake
    implements _i3.$IndustriesTable {
  _Fake$IndustriesTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CobsTable_10 extends _i1.SmartFake implements _i3.$CobsTable {
  _Fake$CobsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LobsTable_11 extends _i1.SmartFake implements _i3.$LobsTable {
  _Fake$LobsTable_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PipelineStagesTable_12 extends _i1.SmartFake
    implements _i3.$PipelineStagesTable {
  _Fake$PipelineStagesTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PipelineStatusesTable_13 extends _i1.SmartFake
    implements _i3.$PipelineStatusesTable {
  _Fake$PipelineStatusesTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ActivityTypesTable_14 extends _i1.SmartFake
    implements _i3.$ActivityTypesTable {
  _Fake$ActivityTypesTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LeadSourcesTable_15 extends _i1.SmartFake
    implements _i3.$LeadSourcesTable {
  _Fake$LeadSourcesTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DeclineReasonsTable_16 extends _i1.SmartFake
    implements _i3.$DeclineReasonsTable {
  _Fake$DeclineReasonsTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CustomersTable_17 extends _i1.SmartFake
    implements _i3.$CustomersTable {
  _Fake$CustomersTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$KeyPersonsTable_18 extends _i1.SmartFake
    implements _i3.$KeyPersonsTable {
  _Fake$KeyPersonsTable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PipelinesTable_19 extends _i1.SmartFake
    implements _i3.$PipelinesTable {
  _Fake$PipelinesTable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PipelineReferralsTable_20 extends _i1.SmartFake
    implements _i3.$PipelineReferralsTable {
  _Fake$PipelineReferralsTable_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ActivitiesTable_21 extends _i1.SmartFake
    implements _i3.$ActivitiesTable {
  _Fake$ActivitiesTable_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ActivityPhotosTable_22 extends _i1.SmartFake
    implements _i3.$ActivityPhotosTable {
  _Fake$ActivityPhotosTable_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ActivityAuditLogsTable_23 extends _i1.SmartFake
    implements _i3.$ActivityAuditLogsTable {
  _Fake$ActivityAuditLogsTable_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HvcTypesTable_24 extends _i1.SmartFake
    implements _i3.$HvcTypesTable {
  _Fake$HvcTypesTable_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HvcsTable_25 extends _i1.SmartFake implements _i3.$HvcsTable {
  _Fake$HvcsTable_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CustomerHvcLinksTable_26 extends _i1.SmartFake
    implements _i3.$CustomerHvcLinksTable {
  _Fake$CustomerHvcLinksTable_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BrokersTable_27 extends _i1.SmartFake implements _i3.$BrokersTable {
  _Fake$BrokersTable_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MeasureDefinitionsTable_28 extends _i1.SmartFake
    implements _i3.$MeasureDefinitionsTable {
  _Fake$MeasureDefinitionsTable_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ScoringPeriodsTable_29 extends _i1.SmartFake
    implements _i3.$ScoringPeriodsTable {
  _Fake$ScoringPeriodsTable_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserTargetsTable_30 extends _i1.SmartFake
    implements _i3.$UserTargetsTable {
  _Fake$UserTargetsTable_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserScoresTable_31 extends _i1.SmartFake
    implements _i3.$UserScoresTable {
  _Fake$UserScoresTable_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserScoreSnapshotsTable_32 extends _i1.SmartFake
    implements _i3.$UserScoreSnapshotsTable {
  _Fake$UserScoreSnapshotsTable_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$WigsTable_33 extends _i1.SmartFake implements _i3.$WigsTable {
  _Fake$WigsTable_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$WigProgressTable_34 extends _i1.SmartFake
    implements _i3.$WigProgressTable {
  _Fake$WigProgressTable_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CadenceScheduleConfigTable_35 extends _i1.SmartFake
    implements _i3.$CadenceScheduleConfigTable {
  _Fake$CadenceScheduleConfigTable_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$CadenceMeetingsTable_36 extends _i1.SmartFake
    implements _i3.$CadenceMeetingsTable {
  _Fake$CadenceMeetingsTable_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CadenceParticipantsTable_37 extends _i1.SmartFake
    implements _i3.$CadenceParticipantsTable {
  _Fake$CadenceParticipantsTable_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NotificationsTable_38 extends _i1.SmartFake
    implements _i3.$NotificationsTable {
  _Fake$NotificationsTable_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NotificationSettingsTable_39 extends _i1.SmartFake
    implements _i3.$NotificationSettingsTable {
  _Fake$NotificationSettingsTable_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AnnouncementsTable_40 extends _i1.SmartFake
    implements _i3.$AnnouncementsTable {
  _Fake$AnnouncementsTable_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AnnouncementReadsTable_41 extends _i1.SmartFake
    implements _i3.$AnnouncementReadsTable {
  _Fake$AnnouncementReadsTable_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncQueueItemsTable_42 extends _i1.SmartFake
    implements _i3.$SyncQueueItemsTable {
  _Fake$SyncQueueItemsTable_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AuditLogsTable_43 extends _i1.SmartFake
    implements _i3.$AuditLogsTable {
  _Fake$AuditLogsTable_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppSettingsTable_44 extends _i1.SmartFake
    implements _i3.$AppSettingsTable {
  _Fake$AppSettingsTable_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PipelineStageHistoryItemsTable_45 extends _i1.SmartFake
    implements _i3.$PipelineStageHistoryItemsTable {
  _Fake$PipelineStageHistoryItemsTable_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$AuditLogCacheTable_46 extends _i1.SmartFake
    implements _i3.$AuditLogCacheTable {
  _Fake$AuditLogCacheTable_46(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_47 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_47(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_48 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_48(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_49 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_49(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_50 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_50(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_51 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_51(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_52 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_52(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_53 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_53(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_54 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_54(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_55 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_55(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_56<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_56(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_57<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_57(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_58<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_58(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_59<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_59(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_60<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_60(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_61<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_61(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_62<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_62(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_63<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_63(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_64 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_64(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_65 extends _i1.SmartFake
    implements _i6.FunctionsClient {
  _FakeFunctionsClient_65(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_66 extends _i1.SmartFake
    implements _i6.SupabaseStorageClient {
  _FakeSupabaseStorageClient_66(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_67 extends _i1.SmartFake
    implements _i6.RealtimeClient {
  _FakeRealtimeClient_67(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_68 extends _i1.SmartFake
    implements _i6.PostgrestClient {
  _FakePostgrestClient_68(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_69 extends _i1.SmartFake implements _i6.GoTrueClient {
  _FakeGoTrueClient_69(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_70 extends _i1.SmartFake
    implements _i6.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_70(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_71 extends _i1.SmartFake
    implements _i6.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_71(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_72<T1> extends _i1.SmartFake
    implements _i6.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_72(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_73 extends _i1.SmartFake
    implements _i6.RealtimeChannel {
  _FakeRealtimeChannel_73(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PipelineLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPipelineLocalDataSource extends _i1.Mock
    implements _i7.PipelineLocalDataSource {
  MockPipelineLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i3.Pipeline>> watchAllPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPipelines, []),
            returnValue: _i5.Stream<List<_i3.Pipeline>>.empty(),
          )
          as _i5.Stream<List<_i3.Pipeline>>);

  @override
  _i5.Stream<List<_i3.Pipeline>> watchCustomerPipelines(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomerPipelines, [customerId]),
            returnValue: _i5.Stream<List<_i3.Pipeline>>.empty(),
          )
          as _i5.Stream<List<_i3.Pipeline>>);

  @override
  _i5.Stream<List<_i3.Pipeline>> watchPipelinesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPipelinesByStage, [stageId]),
            returnValue: _i5.Stream<List<_i3.Pipeline>>.empty(),
          )
          as _i5.Stream<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.Pipeline>> getAllPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPipelines, []),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<_i3.Pipeline?> getPipelineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineById, [id]),
            returnValue: _i5.Future<_i3.Pipeline?>.value(),
          )
          as _i5.Future<_i3.Pipeline?>);

  @override
  _i5.Stream<_i3.Pipeline?> watchPipelineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchPipelineById, [id]),
            returnValue: _i5.Stream<_i3.Pipeline?>.empty(),
          )
          as _i5.Stream<_i3.Pipeline?>);

  @override
  _i5.Stream<List<_i3.Pipeline>> watchBrokerPipelines(String? brokerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBrokerPipelines, [brokerId]),
            returnValue: _i5.Stream<List<_i3.Pipeline>>.empty(),
          )
          as _i5.Stream<List<_i3.Pipeline>>);

  @override
  _i5.Future<_i3.Pipeline?> getPipelineByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineByCode, [code]),
            returnValue: _i5.Future<_i3.Pipeline?>.value(),
          )
          as _i5.Future<_i3.Pipeline?>);

  @override
  _i5.Future<List<_i3.Pipeline>> getCustomerPipelines(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPipelines, [customerId]),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<void> insertPipeline(_i3.PipelinesCompanion? pipeline) =>
      (super.noSuchMethod(
            Invocation.method(#insertPipeline, [pipeline]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePipeline(
    String? id,
    _i3.PipelinesCompanion? pipeline,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePipeline, [id, pipeline]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDeletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeletePipeline, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> hardDeletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeletePipeline, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Pipeline>> searchPipelines(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPipelines, [query]),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.Pipeline>> getPipelinesByAssignedRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelinesByAssignedRm, [rmId]),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.Pipeline>> getPipelinesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelinesByStage, [stageId]),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.Pipeline>> getBrokerPipelines(String? brokerId) =>
      (super.noSuchMethod(
            Invocation.method(#getBrokerPipelines, [brokerId]),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.Pipeline>> getPendingSyncPipelines() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncPipelines, []),
            returnValue: _i5.Future<List<_i3.Pipeline>>.value(<_i3.Pipeline>[]),
          )
          as _i5.Future<List<_i3.Pipeline>>);

  @override
  _i5.Future<List<_i3.PipelineStage>> getPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStages, []),
            returnValue: _i5.Future<List<_i3.PipelineStage>>.value(
              <_i3.PipelineStage>[],
            ),
          )
          as _i5.Future<List<_i3.PipelineStage>>);

  @override
  _i5.Future<List<_i3.PipelineStatuse>> getPipelineStatuses({
    String? stageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStatuses, [], {#stageId: stageId}),
            returnValue: _i5.Future<List<_i3.PipelineStatuse>>.value(
              <_i3.PipelineStatuse>[],
            ),
          )
          as _i5.Future<List<_i3.PipelineStatuse>>);

  @override
  _i5.Future<_i3.PipelineStage?> getStageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStageById, [id]),
            returnValue: _i5.Future<_i3.PipelineStage?>.value(),
          )
          as _i5.Future<_i3.PipelineStage?>);

  @override
  _i5.Future<_i3.PipelineStatuse?> getDefaultStatus(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultStatus, [stageId]),
            returnValue: _i5.Future<_i3.PipelineStatuse?>.value(),
          )
          as _i5.Future<_i3.PipelineStatuse?>);

  @override
  _i5.Future<void> markAsSynced(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id, syncedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertPipelines(List<_i3.PipelinesCompanion>? pipelines) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPipelines, [pipelines]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getPendingSyncCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<DateTime?> getLastSyncTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, []),
            returnValue: _i5.Future<DateTime?>.value(),
          )
          as _i5.Future<DateTime?>);

  @override
  _i5.Future<int> getTotalCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getCountByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getCountByStage, [stageId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getCustomerPipelineCount(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPipelineCount, [customerId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [MasterDataLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterDataLocalDataSource extends _i1.Mock
    implements _i8.MasterDataLocalDataSource {
  MockMasterDataLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.ProvinceDto>> getProvinces() =>
      (super.noSuchMethod(
            Invocation.method(#getProvinces, []),
            returnValue: _i5.Future<List<_i9.ProvinceDto>>.value(
              <_i9.ProvinceDto>[],
            ),
          )
          as _i5.Future<List<_i9.ProvinceDto>>);

  @override
  _i5.Stream<List<_i9.ProvinceDto>> watchProvinces() =>
      (super.noSuchMethod(
            Invocation.method(#watchProvinces, []),
            returnValue: _i5.Stream<List<_i9.ProvinceDto>>.empty(),
          )
          as _i5.Stream<List<_i9.ProvinceDto>>);

  @override
  _i5.Future<List<_i9.CityDto>> getCitiesByProvince(String? provinceId) =>
      (super.noSuchMethod(
            Invocation.method(#getCitiesByProvince, [provinceId]),
            returnValue: _i5.Future<List<_i9.CityDto>>.value(<_i9.CityDto>[]),
          )
          as _i5.Future<List<_i9.CityDto>>);

  @override
  _i5.Stream<List<_i9.CityDto>> watchCitiesByProvince(String? provinceId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCitiesByProvince, [provinceId]),
            returnValue: _i5.Stream<List<_i9.CityDto>>.empty(),
          )
          as _i5.Stream<List<_i9.CityDto>>);

  @override
  _i5.Future<List<_i9.CompanyTypeDto>> getCompanyTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyTypes, []),
            returnValue: _i5.Future<List<_i9.CompanyTypeDto>>.value(
              <_i9.CompanyTypeDto>[],
            ),
          )
          as _i5.Future<List<_i9.CompanyTypeDto>>);

  @override
  _i5.Stream<List<_i9.CompanyTypeDto>> watchCompanyTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchCompanyTypes, []),
            returnValue: _i5.Stream<List<_i9.CompanyTypeDto>>.empty(),
          )
          as _i5.Stream<List<_i9.CompanyTypeDto>>);

  @override
  _i5.Future<List<_i9.OwnershipTypeDto>> getOwnershipTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getOwnershipTypes, []),
            returnValue: _i5.Future<List<_i9.OwnershipTypeDto>>.value(
              <_i9.OwnershipTypeDto>[],
            ),
          )
          as _i5.Future<List<_i9.OwnershipTypeDto>>);

  @override
  _i5.Stream<List<_i9.OwnershipTypeDto>> watchOwnershipTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchOwnershipTypes, []),
            returnValue: _i5.Stream<List<_i9.OwnershipTypeDto>>.empty(),
          )
          as _i5.Stream<List<_i9.OwnershipTypeDto>>);

  @override
  _i5.Future<List<_i9.IndustryDto>> getIndustries() =>
      (super.noSuchMethod(
            Invocation.method(#getIndustries, []),
            returnValue: _i5.Future<List<_i9.IndustryDto>>.value(
              <_i9.IndustryDto>[],
            ),
          )
          as _i5.Future<List<_i9.IndustryDto>>);

  @override
  _i5.Stream<List<_i9.IndustryDto>> watchIndustries() =>
      (super.noSuchMethod(
            Invocation.method(#watchIndustries, []),
            returnValue: _i5.Stream<List<_i9.IndustryDto>>.empty(),
          )
          as _i5.Stream<List<_i9.IndustryDto>>);

  @override
  _i5.Future<List<_i9.CobDto>> getCobs() =>
      (super.noSuchMethod(
            Invocation.method(#getCobs, []),
            returnValue: _i5.Future<List<_i9.CobDto>>.value(<_i9.CobDto>[]),
          )
          as _i5.Future<List<_i9.CobDto>>);

  @override
  _i5.Stream<List<_i9.CobDto>> watchCobs() =>
      (super.noSuchMethod(
            Invocation.method(#watchCobs, []),
            returnValue: _i5.Stream<List<_i9.CobDto>>.empty(),
          )
          as _i5.Stream<List<_i9.CobDto>>);

  @override
  _i5.Future<List<_i9.LobDto>> getLobsByCob(String? cobId) =>
      (super.noSuchMethod(
            Invocation.method(#getLobsByCob, [cobId]),
            returnValue: _i5.Future<List<_i9.LobDto>>.value(<_i9.LobDto>[]),
          )
          as _i5.Future<List<_i9.LobDto>>);

  @override
  _i5.Stream<List<_i9.LobDto>> watchLobsByCob(String? cobId) =>
      (super.noSuchMethod(
            Invocation.method(#watchLobsByCob, [cobId]),
            returnValue: _i5.Stream<List<_i9.LobDto>>.empty(),
          )
          as _i5.Stream<List<_i9.LobDto>>);

  @override
  _i5.Future<List<_i9.LobDto>> getAllLobs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLobs, []),
            returnValue: _i5.Future<List<_i9.LobDto>>.value(<_i9.LobDto>[]),
          )
          as _i5.Future<List<_i9.LobDto>>);

  @override
  _i5.Future<List<_i9.PipelineStageDto>> getPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineStages, []),
            returnValue: _i5.Future<List<_i9.PipelineStageDto>>.value(
              <_i9.PipelineStageDto>[],
            ),
          )
          as _i5.Future<List<_i9.PipelineStageDto>>);

  @override
  _i5.Stream<List<_i9.PipelineStageDto>> watchPipelineStages() =>
      (super.noSuchMethod(
            Invocation.method(#watchPipelineStages, []),
            returnValue: _i5.Stream<List<_i9.PipelineStageDto>>.empty(),
          )
          as _i5.Stream<List<_i9.PipelineStageDto>>);

  @override
  _i5.Future<List<_i9.PipelineStatusDto>> getStatusesByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getStatusesByStage, [stageId]),
            returnValue: _i5.Future<List<_i9.PipelineStatusDto>>.value(
              <_i9.PipelineStatusDto>[],
            ),
          )
          as _i5.Future<List<_i9.PipelineStatusDto>>);

  @override
  _i5.Future<List<_i9.ActivityTypeDto>> getActivityTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getActivityTypes, []),
            returnValue: _i5.Future<List<_i9.ActivityTypeDto>>.value(
              <_i9.ActivityTypeDto>[],
            ),
          )
          as _i5.Future<List<_i9.ActivityTypeDto>>);

  @override
  _i5.Stream<List<_i9.ActivityTypeDto>> watchActivityTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchActivityTypes, []),
            returnValue: _i5.Stream<List<_i9.ActivityTypeDto>>.empty(),
          )
          as _i5.Stream<List<_i9.ActivityTypeDto>>);

  @override
  _i5.Future<List<_i9.LeadSourceDto>> getLeadSources() =>
      (super.noSuchMethod(
            Invocation.method(#getLeadSources, []),
            returnValue: _i5.Future<List<_i9.LeadSourceDto>>.value(
              <_i9.LeadSourceDto>[],
            ),
          )
          as _i5.Future<List<_i9.LeadSourceDto>>);

  @override
  _i5.Stream<List<_i9.LeadSourceDto>> watchLeadSources() =>
      (super.noSuchMethod(
            Invocation.method(#watchLeadSources, []),
            returnValue: _i5.Stream<List<_i9.LeadSourceDto>>.empty(),
          )
          as _i5.Stream<List<_i9.LeadSourceDto>>);

  @override
  _i5.Future<List<_i9.DeclineReasonDto>> getDeclineReasons() =>
      (super.noSuchMethod(
            Invocation.method(#getDeclineReasons, []),
            returnValue: _i5.Future<List<_i9.DeclineReasonDto>>.value(
              <_i9.DeclineReasonDto>[],
            ),
          )
          as _i5.Future<List<_i9.DeclineReasonDto>>);

  @override
  _i5.Future<List<_i9.HvcTypeDto>> getHvcTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getHvcTypes, []),
            returnValue: _i5.Future<List<_i9.HvcTypeDto>>.value(
              <_i9.HvcTypeDto>[],
            ),
          )
          as _i5.Future<List<_i9.HvcTypeDto>>);

  @override
  _i5.Stream<List<_i9.HvcTypeDto>> watchHvcTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchHvcTypes, []),
            returnValue: _i5.Stream<List<_i9.HvcTypeDto>>.empty(),
          )
          as _i5.Stream<List<_i9.HvcTypeDto>>);

  @override
  _i5.Future<List<_i3.Broker>> getBrokers() =>
      (super.noSuchMethod(
            Invocation.method(#getBrokers, []),
            returnValue: _i5.Future<List<_i3.Broker>>.value(<_i3.Broker>[]),
          )
          as _i5.Future<List<_i3.Broker>>);

  @override
  _i5.Stream<List<_i3.Broker>> watchBrokers() =>
      (super.noSuchMethod(
            Invocation.method(#watchBrokers, []),
            returnValue: _i5.Stream<List<_i3.Broker>>.empty(),
          )
          as _i5.Stream<List<_i3.Broker>>);

  @override
  _i5.Future<void> upsertProvinces(List<_i3.ProvincesCompanion>? provinces) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProvinces, [provinces]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertCities(List<_i3.CitiesCompanion>? cities) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCities, [cities]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertCompanyTypes(List<_i3.CompanyTypesCompanion>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCompanyTypes, [items]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertOwnershipTypes(
    List<_i3.OwnershipTypesCompanion>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertOwnershipTypes, [items]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertIndustries(List<_i3.IndustriesCompanion>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertIndustries, [items]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i9.RegionalOfficeDto>> watchRegionalOffices() =>
      (super.noSuchMethod(
            Invocation.method(#watchRegionalOffices, []),
            returnValue: _i5.Stream<List<_i9.RegionalOfficeDto>>.empty(),
          )
          as _i5.Stream<List<_i9.RegionalOfficeDto>>);

  @override
  _i5.Stream<List<_i9.BranchDto>> watchBranches() =>
      (super.noSuchMethod(
            Invocation.method(#watchBranches, []),
            returnValue: _i5.Stream<List<_i9.BranchDto>>.empty(),
          )
          as _i5.Stream<List<_i9.BranchDto>>);
}

/// A class which mocks [CustomerLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerLocalDataSource extends _i1.Mock
    implements _i10.CustomerLocalDataSource {
  MockCustomerLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i3.Customer>> watchAllCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCustomers, []),
            returnValue: _i5.Stream<List<_i3.Customer>>.empty(),
          )
          as _i5.Stream<List<_i3.Customer>>);

  @override
  _i5.Stream<List<_i3.Customer>> watchCustomersByRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomersByRm, [rmId]),
            returnValue: _i5.Stream<List<_i3.Customer>>.empty(),
          )
          as _i5.Stream<List<_i3.Customer>>);

  @override
  _i5.Stream<_i3.Customer?> watchCustomerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchCustomerById, [id]),
            returnValue: _i5.Stream<_i3.Customer?>.empty(),
          )
          as _i5.Stream<_i3.Customer?>);

  @override
  _i5.Future<List<_i3.Customer>> getAllCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCustomers, []),
            returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
          )
          as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<_i3.Customer?> getCustomerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerById, [id]),
            returnValue: _i5.Future<_i3.Customer?>.value(),
          )
          as _i5.Future<_i3.Customer?>);

  @override
  _i5.Future<_i3.Customer?> getCustomerByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerByCode, [code]),
            returnValue: _i5.Future<_i3.Customer?>.value(),
          )
          as _i5.Future<_i3.Customer?>);

  @override
  _i5.Future<void> insertCustomer(_i3.CustomersCompanion? customer) =>
      (super.noSuchMethod(
            Invocation.method(#insertCustomer, [customer]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateCustomer(
    String? id,
    _i3.CustomersCompanion? customer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [id, customer]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDeleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteCustomer, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> hardDeleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteCustomer, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Customer>> searchCustomers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCustomers, [query]),
            returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
          )
          as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<List<_i3.Customer>> getCustomersByAssignedRm(String? rmId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersByAssignedRm, [rmId]),
            returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
          )
          as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<List<_i3.Customer>> getPendingSyncCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCustomers, []),
            returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
          )
          as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<List<_i3.Customer>> getActiveCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCustomers, []),
            returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
          )
          as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<void> markAsSynced(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id, syncedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertCustomers(List<_i3.CustomersCompanion>? customers) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCustomers, [customers]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getPendingSyncCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<DateTime?> getLastSyncTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, []),
            returnValue: _i5.Future<DateTime?>.value(),
          )
          as _i5.Future<DateTime?>);

  @override
  _i5.Future<int> getTotalCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getActiveCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [PipelineRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPipelineRemoteDataSource extends _i1.Mock
    implements _i11.PipelineRemoteDataSource {
  MockPipelineRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<Map<String, dynamic>>> fetchPipelines({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelines, [], {#since: since}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> fetchPipelinesByCustomer(
    String? customerId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchPipelinesByCustomer,
              [customerId],
              {#since: since},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> fetchPipelinesByRm(
    String? rmId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelinesByRm, [rmId], {#since: since}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> fetchPipelineById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPipelineById, [id]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>> createPipeline(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createPipeline, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> updatePipeline(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePipeline, [id, data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deletePipeline(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePipeline, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> upsertPipeline(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPipeline, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<int> getPipelineCountByCustomer(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineCountByCustomer, [customerId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getPipelineCountByStage(String? stageId) =>
      (super.noSuchMethod(
            Invocation.method(#getPipelineCountByStage, [stageId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$RegionalOfficesTable get regionalOffices =>
      (super.noSuchMethod(
            Invocation.getter(#regionalOffices),
            returnValue: _Fake$RegionalOfficesTable_1(
              this,
              Invocation.getter(#regionalOffices),
            ),
          )
          as _i3.$RegionalOfficesTable);

  @override
  _i3.$BranchesTable get branches =>
      (super.noSuchMethod(
            Invocation.getter(#branches),
            returnValue: _Fake$BranchesTable_2(
              this,
              Invocation.getter(#branches),
            ),
          )
          as _i3.$BranchesTable);

  @override
  _i3.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_3(this, Invocation.getter(#users)),
          )
          as _i3.$UsersTable);

  @override
  _i3.$UserHierarchyTable get userHierarchy =>
      (super.noSuchMethod(
            Invocation.getter(#userHierarchy),
            returnValue: _Fake$UserHierarchyTable_4(
              this,
              Invocation.getter(#userHierarchy),
            ),
          )
          as _i3.$UserHierarchyTable);

  @override
  _i3.$ProvincesTable get provinces =>
      (super.noSuchMethod(
            Invocation.getter(#provinces),
            returnValue: _Fake$ProvincesTable_5(
              this,
              Invocation.getter(#provinces),
            ),
          )
          as _i3.$ProvincesTable);

  @override
  _i3.$CitiesTable get cities =>
      (super.noSuchMethod(
            Invocation.getter(#cities),
            returnValue: _Fake$CitiesTable_6(this, Invocation.getter(#cities)),
          )
          as _i3.$CitiesTable);

  @override
  _i3.$CompanyTypesTable get companyTypes =>
      (super.noSuchMethod(
            Invocation.getter(#companyTypes),
            returnValue: _Fake$CompanyTypesTable_7(
              this,
              Invocation.getter(#companyTypes),
            ),
          )
          as _i3.$CompanyTypesTable);

  @override
  _i3.$OwnershipTypesTable get ownershipTypes =>
      (super.noSuchMethod(
            Invocation.getter(#ownershipTypes),
            returnValue: _Fake$OwnershipTypesTable_8(
              this,
              Invocation.getter(#ownershipTypes),
            ),
          )
          as _i3.$OwnershipTypesTable);

  @override
  _i3.$IndustriesTable get industries =>
      (super.noSuchMethod(
            Invocation.getter(#industries),
            returnValue: _Fake$IndustriesTable_9(
              this,
              Invocation.getter(#industries),
            ),
          )
          as _i3.$IndustriesTable);

  @override
  _i3.$CobsTable get cobs =>
      (super.noSuchMethod(
            Invocation.getter(#cobs),
            returnValue: _Fake$CobsTable_10(this, Invocation.getter(#cobs)),
          )
          as _i3.$CobsTable);

  @override
  _i3.$LobsTable get lobs =>
      (super.noSuchMethod(
            Invocation.getter(#lobs),
            returnValue: _Fake$LobsTable_11(this, Invocation.getter(#lobs)),
          )
          as _i3.$LobsTable);

  @override
  _i3.$PipelineStagesTable get pipelineStages =>
      (super.noSuchMethod(
            Invocation.getter(#pipelineStages),
            returnValue: _Fake$PipelineStagesTable_12(
              this,
              Invocation.getter(#pipelineStages),
            ),
          )
          as _i3.$PipelineStagesTable);

  @override
  _i3.$PipelineStatusesTable get pipelineStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#pipelineStatuses),
            returnValue: _Fake$PipelineStatusesTable_13(
              this,
              Invocation.getter(#pipelineStatuses),
            ),
          )
          as _i3.$PipelineStatusesTable);

  @override
  _i3.$ActivityTypesTable get activityTypes =>
      (super.noSuchMethod(
            Invocation.getter(#activityTypes),
            returnValue: _Fake$ActivityTypesTable_14(
              this,
              Invocation.getter(#activityTypes),
            ),
          )
          as _i3.$ActivityTypesTable);

  @override
  _i3.$LeadSourcesTable get leadSources =>
      (super.noSuchMethod(
            Invocation.getter(#leadSources),
            returnValue: _Fake$LeadSourcesTable_15(
              this,
              Invocation.getter(#leadSources),
            ),
          )
          as _i3.$LeadSourcesTable);

  @override
  _i3.$DeclineReasonsTable get declineReasons =>
      (super.noSuchMethod(
            Invocation.getter(#declineReasons),
            returnValue: _Fake$DeclineReasonsTable_16(
              this,
              Invocation.getter(#declineReasons),
            ),
          )
          as _i3.$DeclineReasonsTable);

  @override
  _i3.$CustomersTable get customers =>
      (super.noSuchMethod(
            Invocation.getter(#customers),
            returnValue: _Fake$CustomersTable_17(
              this,
              Invocation.getter(#customers),
            ),
          )
          as _i3.$CustomersTable);

  @override
  _i3.$KeyPersonsTable get keyPersons =>
      (super.noSuchMethod(
            Invocation.getter(#keyPersons),
            returnValue: _Fake$KeyPersonsTable_18(
              this,
              Invocation.getter(#keyPersons),
            ),
          )
          as _i3.$KeyPersonsTable);

  @override
  _i3.$PipelinesTable get pipelines =>
      (super.noSuchMethod(
            Invocation.getter(#pipelines),
            returnValue: _Fake$PipelinesTable_19(
              this,
              Invocation.getter(#pipelines),
            ),
          )
          as _i3.$PipelinesTable);

  @override
  _i3.$PipelineReferralsTable get pipelineReferrals =>
      (super.noSuchMethod(
            Invocation.getter(#pipelineReferrals),
            returnValue: _Fake$PipelineReferralsTable_20(
              this,
              Invocation.getter(#pipelineReferrals),
            ),
          )
          as _i3.$PipelineReferralsTable);

  @override
  _i3.$ActivitiesTable get activities =>
      (super.noSuchMethod(
            Invocation.getter(#activities),
            returnValue: _Fake$ActivitiesTable_21(
              this,
              Invocation.getter(#activities),
            ),
          )
          as _i3.$ActivitiesTable);

  @override
  _i3.$ActivityPhotosTable get activityPhotos =>
      (super.noSuchMethod(
            Invocation.getter(#activityPhotos),
            returnValue: _Fake$ActivityPhotosTable_22(
              this,
              Invocation.getter(#activityPhotos),
            ),
          )
          as _i3.$ActivityPhotosTable);

  @override
  _i3.$ActivityAuditLogsTable get activityAuditLogs =>
      (super.noSuchMethod(
            Invocation.getter(#activityAuditLogs),
            returnValue: _Fake$ActivityAuditLogsTable_23(
              this,
              Invocation.getter(#activityAuditLogs),
            ),
          )
          as _i3.$ActivityAuditLogsTable);

  @override
  _i3.$HvcTypesTable get hvcTypes =>
      (super.noSuchMethod(
            Invocation.getter(#hvcTypes),
            returnValue: _Fake$HvcTypesTable_24(
              this,
              Invocation.getter(#hvcTypes),
            ),
          )
          as _i3.$HvcTypesTable);

  @override
  _i3.$HvcsTable get hvcs =>
      (super.noSuchMethod(
            Invocation.getter(#hvcs),
            returnValue: _Fake$HvcsTable_25(this, Invocation.getter(#hvcs)),
          )
          as _i3.$HvcsTable);

  @override
  _i3.$CustomerHvcLinksTable get customerHvcLinks =>
      (super.noSuchMethod(
            Invocation.getter(#customerHvcLinks),
            returnValue: _Fake$CustomerHvcLinksTable_26(
              this,
              Invocation.getter(#customerHvcLinks),
            ),
          )
          as _i3.$CustomerHvcLinksTable);

  @override
  _i3.$BrokersTable get brokers =>
      (super.noSuchMethod(
            Invocation.getter(#brokers),
            returnValue: _Fake$BrokersTable_27(
              this,
              Invocation.getter(#brokers),
            ),
          )
          as _i3.$BrokersTable);

  @override
  _i3.$MeasureDefinitionsTable get measureDefinitions =>
      (super.noSuchMethod(
            Invocation.getter(#measureDefinitions),
            returnValue: _Fake$MeasureDefinitionsTable_28(
              this,
              Invocation.getter(#measureDefinitions),
            ),
          )
          as _i3.$MeasureDefinitionsTable);

  @override
  _i3.$ScoringPeriodsTable get scoringPeriods =>
      (super.noSuchMethod(
            Invocation.getter(#scoringPeriods),
            returnValue: _Fake$ScoringPeriodsTable_29(
              this,
              Invocation.getter(#scoringPeriods),
            ),
          )
          as _i3.$ScoringPeriodsTable);

  @override
  _i3.$UserTargetsTable get userTargets =>
      (super.noSuchMethod(
            Invocation.getter(#userTargets),
            returnValue: _Fake$UserTargetsTable_30(
              this,
              Invocation.getter(#userTargets),
            ),
          )
          as _i3.$UserTargetsTable);

  @override
  _i3.$UserScoresTable get userScores =>
      (super.noSuchMethod(
            Invocation.getter(#userScores),
            returnValue: _Fake$UserScoresTable_31(
              this,
              Invocation.getter(#userScores),
            ),
          )
          as _i3.$UserScoresTable);

  @override
  _i3.$UserScoreSnapshotsTable get userScoreSnapshots =>
      (super.noSuchMethod(
            Invocation.getter(#userScoreSnapshots),
            returnValue: _Fake$UserScoreSnapshotsTable_32(
              this,
              Invocation.getter(#userScoreSnapshots),
            ),
          )
          as _i3.$UserScoreSnapshotsTable);

  @override
  _i3.$WigsTable get wigs =>
      (super.noSuchMethod(
            Invocation.getter(#wigs),
            returnValue: _Fake$WigsTable_33(this, Invocation.getter(#wigs)),
          )
          as _i3.$WigsTable);

  @override
  _i3.$WigProgressTable get wigProgress =>
      (super.noSuchMethod(
            Invocation.getter(#wigProgress),
            returnValue: _Fake$WigProgressTable_34(
              this,
              Invocation.getter(#wigProgress),
            ),
          )
          as _i3.$WigProgressTable);

  @override
  _i3.$CadenceScheduleConfigTable get cadenceScheduleConfig =>
      (super.noSuchMethod(
            Invocation.getter(#cadenceScheduleConfig),
            returnValue: _Fake$CadenceScheduleConfigTable_35(
              this,
              Invocation.getter(#cadenceScheduleConfig),
            ),
          )
          as _i3.$CadenceScheduleConfigTable);

  @override
  _i3.$CadenceMeetingsTable get cadenceMeetings =>
      (super.noSuchMethod(
            Invocation.getter(#cadenceMeetings),
            returnValue: _Fake$CadenceMeetingsTable_36(
              this,
              Invocation.getter(#cadenceMeetings),
            ),
          )
          as _i3.$CadenceMeetingsTable);

  @override
  _i3.$CadenceParticipantsTable get cadenceParticipants =>
      (super.noSuchMethod(
            Invocation.getter(#cadenceParticipants),
            returnValue: _Fake$CadenceParticipantsTable_37(
              this,
              Invocation.getter(#cadenceParticipants),
            ),
          )
          as _i3.$CadenceParticipantsTable);

  @override
  _i3.$NotificationsTable get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _Fake$NotificationsTable_38(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i3.$NotificationsTable);

  @override
  _i3.$NotificationSettingsTable get notificationSettings =>
      (super.noSuchMethod(
            Invocation.getter(#notificationSettings),
            returnValue: _Fake$NotificationSettingsTable_39(
              this,
              Invocation.getter(#notificationSettings),
            ),
          )
          as _i3.$NotificationSettingsTable);

  @override
  _i3.$AnnouncementsTable get announcements =>
      (super.noSuchMethod(
            Invocation.getter(#announcements),
            returnValue: _Fake$AnnouncementsTable_40(
              this,
              Invocation.getter(#announcements),
            ),
          )
          as _i3.$AnnouncementsTable);

  @override
  _i3.$AnnouncementReadsTable get announcementReads =>
      (super.noSuchMethod(
            Invocation.getter(#announcementReads),
            returnValue: _Fake$AnnouncementReadsTable_41(
              this,
              Invocation.getter(#announcementReads),
            ),
          )
          as _i3.$AnnouncementReadsTable);

  @override
  _i3.$SyncQueueItemsTable get syncQueueItems =>
      (super.noSuchMethod(
            Invocation.getter(#syncQueueItems),
            returnValue: _Fake$SyncQueueItemsTable_42(
              this,
              Invocation.getter(#syncQueueItems),
            ),
          )
          as _i3.$SyncQueueItemsTable);

  @override
  _i3.$AuditLogsTable get auditLogs =>
      (super.noSuchMethod(
            Invocation.getter(#auditLogs),
            returnValue: _Fake$AuditLogsTable_43(
              this,
              Invocation.getter(#auditLogs),
            ),
          )
          as _i3.$AuditLogsTable);

  @override
  _i3.$AppSettingsTable get appSettings =>
      (super.noSuchMethod(
            Invocation.getter(#appSettings),
            returnValue: _Fake$AppSettingsTable_44(
              this,
              Invocation.getter(#appSettings),
            ),
          )
          as _i3.$AppSettingsTable);

  @override
  _i3.$PipelineStageHistoryItemsTable get pipelineStageHistoryItems =>
      (super.noSuchMethod(
            Invocation.getter(#pipelineStageHistoryItems),
            returnValue: _Fake$PipelineStageHistoryItemsTable_45(
              this,
              Invocation.getter(#pipelineStageHistoryItems),
            ),
          )
          as _i3.$PipelineStageHistoryItemsTable);

  @override
  _i3.$AuditLogCacheTable get auditLogCache =>
      (super.noSuchMethod(
            Invocation.getter(#auditLogCache),
            returnValue: _Fake$AuditLogCacheTable_46(
              this,
              Invocation.getter(#auditLogCache),
            ),
          )
          as _i3.$AuditLogCacheTable);

  @override
  _i3.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_47(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$AppDatabaseManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_48(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_49(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_50(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_51(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i12.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_52(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_53(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_54(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_55(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i12.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_56<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_57<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_58<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_59<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_60<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_61<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_62<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_63<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_63<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_56<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_56<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_56<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_64(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_64(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i6.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_65(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i6.FunctionsClient);

  @override
  _i6.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_66(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i6.SupabaseStorageClient);

  @override
  _i6.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_67(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i6.RealtimeClient);

  @override
  _i6.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_68(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i6.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_69(this, Invocation.getter(#auth)),
          )
          as _i6.GoTrueClient);

  @override
  set functions(_i6.FunctionsClient? _functions) => super.noSuchMethod(
    Invocation.setter(#functions, _functions),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i6.SupabaseStorageClient? _storage) => super.noSuchMethod(
    Invocation.setter(#storage, _storage),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i6.RealtimeClient? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i6.PostgrestClient? _rest) => super.noSuchMethod(
    Invocation.setter(#rest, _rest),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i6.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_70(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i6.SupabaseQueryBuilder);

  @override
  _i6.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_71(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i6.SupabaseQuerySchema);

  @override
  _i6.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_72<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i6.PostgrestFilterBuilder<T>);

  @override
  _i6.RealtimeChannel channel(
    String? name, {
    _i6.RealtimeChannelConfig? opts = const _i6.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_73(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i6.RealtimeChannel);

  @override
  List<_i6.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i6.RealtimeChannel>[],
          )
          as List<_i6.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i6.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i5.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
